version: '3'
services:
  www:
    container_name: 'simplerisk-www'
    build:
      context: ./simplerisk/
      args:
        - simplerisk_build_artefact=simplerisk.tgz
        - db_ssl_cert=BaltimoreCyberTrustRoot.crt.pem
    environment:
      - MYSQL_SSL_CERTIFICATE_PATH
      - MYSQL_HOSTNAME
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - PRIVATE_KEY
      - CERTIFICATE
    volumes:
      - ./data/logs/www:/var/log/apache2
    ports:
      - "8080:80"
      - "8443:443"
