version: '3'
services:
  www:
    container_name: 'simplerisk-www'
    build:
      context: ./simplerisk/
    environment:
      - MYSQL_HOSTNAME
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - PRIVATE_KEY
      - CERTIFICATE
    volumes:
      - ./data/logs/www:/var/log/apache2
    ports:
      - "8080:80"
      - "8443:443"
